<<<<<<< Updated upstream
# Generated by Django 5.0.7 on 2024-08-31 14:06
=======
# Generated by Django 5.0.7 on 2024-08-27 08:39
>>>>>>> Stashed changes

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< Updated upstream
            name='Signup_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Conform_Password', models.CharField(max_length=50)),
=======
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
>>>>>>> Stashed changes
            ],
        ),
    ]
