# Generated by Django 3.0.1 on 2025-01-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webSec', '0002_auto_20241107_1917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
